server:
  port: 8755

zuul:
  prefix: /api
  routes:
        details:
            path: /details/**
            serviceId: details-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/        