spring:
  application:
    name: EurekaServer

server:
  port: ${PORT:8761}
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
